/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smartcityg;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class add_job_op extends javax.swing.JFrame {

    /**
     * Creates new form add_job_op
     */
    String name;
    public add_job_op() {
        initComponents();
    }

    public add_job_op(String nam) {
        initComponents();
        table.setRowHeight(30);
        name = nam;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        offer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yoe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(930, 620));
        setMinimumSize(new java.awt.Dimension(930, 620));
        setPreferredSize(new java.awt.Dimension(930, 620));
        getContentPane().setLayout(null);

        table.setBackground(new java.awt.Color(95, 17, 131));
        table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Offering", "Years of Experience"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 250, 650, 330);

        offer.setBackground(new java.awt.Color(95, 17, 131));
        offer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        offer.setForeground(new java.awt.Color(255, 255, 255));
        offer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offerActionPerformed(evt);
            }
        });
        offer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                offerKeyPressed(evt);
            }
        });
        getContentPane().add(offer);
        offer.setBounds(70, 140, 200, 30);

        jLabel2.setBackground(new java.awt.Color(95, 17, 131));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Offering Amount");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 90, 220, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Rs");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 140, 20, 30);

        yoe.setBackground(new java.awt.Color(95, 17, 131));
        yoe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        yoe.setForeground(new java.awt.Color(255, 255, 255));
        yoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoeActionPerformed(evt);
            }
        });
        yoe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                yoeKeyPressed(evt);
            }
        });
        getContentPane().add(yoe);
        yoe.setBounds(430, 140, 230, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Years of Experience");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 100, 240, 30);

        jButton1.setBackground(new java.awt.Color(95, 17, 131));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("add job ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(760, 190, 120, 30);

        jButton2.setBackground(new java.awt.Color(95, 17, 131));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Done");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(760, 250, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smartcityg/modern-city-at-night-cartoon-background-vector-23716650.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 930, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_yoeActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
            offer.setBorder(new LineBorder(Color.WHITE, 1));
            yoe.setBorder(new LineBorder(Color.WHITE, 1));

        if (offer.getText().equals(null) || offer.getText().equals("")) {
            offer.setBorder(new LineBorder(Color.red, 1));
        } else if (yoe.getText().equals("") || yoe.getText().equals(null)) {
            yoe.setBorder(new LineBorder(Color.red, 1));

        } 
        else{
            
                try {
                    FileWriter fw = new FileWriter("jobs", true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    PrintWriter pw = new PrintWriter(bw);
                    pw.println(name + "," + offer.getText() + "," + yoe.getText());

                    pw.flush();
                    pw.close();
                    bw.close();
                    fw.close();

                } catch (IOException e) {
                }

                String data[] = {offer.getText(), yoe.getText()};
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.addRow(data);
                
               offer.setText("");
                yoe.setText("");

            }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void offerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offerActionPerformed

    private void offerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_offerKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            offer.setEditable(false);
        } else {
            offer.setEditable(true);
        }
    }//GEN-LAST:event_offerKeyPressed

    private void yoeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yoeKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
           yoe.setEditable(false);
        } else {
            yoe.setEditable(true);
        }
    }//GEN-LAST:event_yoeKeyPressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new admin_logged().setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_job_op.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_job_op.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_job_op.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_job_op.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_job_op().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField offer;
    private javax.swing.JTable table;
    private javax.swing.JTextField yoe;
    // End of variables declaration//GEN-END:variables
}
