/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smartcityg;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author USER
 */
public class stu_logged extends javax.swing.JFrame {

    /**
     * Creates new form stu_logged
     */
    String name;
    String pass;
    String ins = "x";
    String gpaa = "x";
    String add;
    String email, gender;
    String aa;
    String bb, id;
    int t;

    public stu_logged(String ids, String nam, String pas, String i, String gp, String em, String ad) {
        name = nam;
        System.out.println(id);
        pass = pas;
        ins = i;
        gpaa = gp;
        add = ad;
        email = em;
        id = ids;
        aa = "Institute Name";
        bb = "GPA";
        t = 2;

        initComponents();
        but.setText("Scholarships");

    }

    public stu_logged() {
        initComponents();

    }

    public stu_logged(String ids, String nam, String pas, String em, String ad, String work, String sal, int t) {
        name = nam;
        pass = pas;
        System.out.println(id);
        ins = work;
        gpaa = sal;
        add = ad;
        email = em;
        aa = "Workplace Name";
        bb = "Salary";
        t = 1;
        id = ids;

        initComponents();

        but.setText("Jobs");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ins_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ins_n = new javax.swing.JLabel();
        gpa = new javax.swing.JLabel();
        gpaf = new javax.swing.JTextField();
        namef1 = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        passf = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        emailf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        but = new javax.swing.JButton();
        insf = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smartcityg/modern-city-at-night-cartoon-background-vector-23716650.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(930, 620));
        setMinimumSize(new java.awt.Dimension(930, 620));
        setPreferredSize(new java.awt.Dimension(930, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(51, 0, 153));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 40));

        jLabel3.setBackground(new java.awt.Color(51, 0, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 80, 40));

        ins_name.setText(ins);
        ins_name.setEditable(false);
        ins_name.setBackground(new java.awt.Color(95, 17, 131));
        ins_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ins_name.setForeground(new java.awt.Color(255, 255, 255));
        ins_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_nameActionPerformed(evt);
            }
        });
        getContentPane().add(ins_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 200, 40));

        jLabel5.setBackground(new java.awt.Color(51, 0, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 140, 40));

        addf.setText(add);
        addf.setEditable(false);
        addf.setBackground(new java.awt.Color(95, 17, 131));
        addf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addf.setForeground(new java.awt.Color(255, 255, 255));
        addf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfActionPerformed(evt);
            }
        });
        getContentPane().add(addf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 190, 40));

        jLabel4.setBackground(new java.awt.Color(51, 0, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 130, 40));

        ins_n.setText(aa);
        ins_n.setVisible(true);
        ins_n.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ins_n.setForeground(new java.awt.Color(255, 255, 255));
        ins_n.setText(aa);
        getContentPane().add(ins_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 210, -1));

        gpa.setText(bb);
        gpa.setVisible(true);
        gpa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        gpa.setForeground(new java.awt.Color(255, 255, 255));
        gpa.setText(bb);
        getContentPane().add(gpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 150, -1));

        gpaf.setText(gpaa);
        gpaf.setEditable(false);
        gpaf.setBackground(new java.awt.Color(95, 17, 131));
        gpaf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gpaf.setForeground(new java.awt.Color(255, 255, 255));
        gpaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpafActionPerformed(evt);
            }
        });
        gpaf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gpafKeyPressed(evt);
            }
        });
        getContentPane().add(gpaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 451, 180, 40));

        namef1.setText(name);
        namef1.setEditable(false);
        namef1.setBackground(new java.awt.Color(95, 17, 131));
        namef1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namef1.setForeground(new java.awt.Color(255, 255, 255));
        namef1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namef1ActionPerformed(evt);
            }
        });
        getContentPane().add(namef1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 40));

        edit.setBackground(new java.awt.Color(95, 17, 131));
        edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit details");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 196, 140, 30));

        combo.setVisible(false);
        combo.setBackground(new java.awt.Color(95, 17, 131));
        combo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        combo.setForeground(new java.awt.Color(255, 255, 255));
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 190, 40));

        passf.setText(pass);
        passf.setEditable(false);
        passf.setBackground(new java.awt.Color(95, 17, 131));
        passf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passf.setForeground(new java.awt.Color(255, 255, 255));
        passf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passfActionPerformed(evt);
            }
        });
        getContentPane().add(passf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, 40));

        jButton2.setBackground(new java.awt.Color(95, 17, 131));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("logout");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 140, 30));

        emailf.setText(email);
        emailf.setEditable(false);
        emailf.setBackground(new java.awt.Color(95, 17, 131));
        emailf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailf.setForeground(new java.awt.Color(255, 255, 255));
        emailf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfActionPerformed(evt);
            }
        });
        getContentPane().add(emailf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 190, 40));

        jButton1.setVisible(false);
        jButton1.setBackground(new java.awt.Color(95, 17, 131));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Set Details");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 140, 30));

        back.setBackground(new java.awt.Color(95, 17, 131));
        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        but.setBackground(new java.awt.Color(95, 17, 131));
        but.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but.setForeground(new java.awt.Color(255, 255, 255));
        but.setText("Schorlarships");
        but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butMouseClicked(evt);
            }
        });
        getContentPane().add(but, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 140, 30));

        insf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smartcityg/modern-city-at-night-cartoon-background-vector-23716650.jpg"))); // NOI18N
        insf.setText("jLabel1");
        getContentPane().add(insf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ins_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_nameActionPerformed

    private void addfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addfActionPerformed

    private void gpafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpafActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpafActionPerformed

    private void gpafKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gpafKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            gpaf.setEditable(false);
        } else {
            gpaf.setEditable(true);
        }
    }//GEN-LAST:event_gpafKeyPressed

    private void namef1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namef1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namef1ActionPerformed

    private void passfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passfActionPerformed

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        // TODO add your handling code here:
        addf.setEditable(true);
        emailf.setEditable(true);
        gpaf.setEditable(true);
        ins_name.setVisible(false);
        combo.setVisible(true);
        edit.setVisible(false);
        jButton1.setVisible(true);
        namef1.setEditable(true);
        passf.setEditable(true);

    }//GEN-LAST:event_editMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setVisible(false);
        new main_menu().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void emailfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        if (t == 2) {
            namef1.setBorder(new LineBorder(Color.white, 1));
            passf.setBorder(new LineBorder(Color.white, 1));
            emailf.setBorder(new LineBorder(Color.white, 1));
            addf.setBorder(new LineBorder(Color.white, 1));
            gpaf.setBorder(new LineBorder(Color.white, 1));
            ins_name.setBorder(new LineBorder(Color.white, 1));

            if (namef1.getText().equals("") || namef1.getText().equals(null)) {
                namef1.setBorder(new LineBorder(Color.red, 1));
            } else if (passf.getText().equals("") || passf.getText().equals(null)) {
                passf.setBorder(new LineBorder(Color.red, 1));
            } else if (emailf.getText().equals("") || emailf.getText().equals(null) || !emailf.getText().contains("@")) {
                emailf.setBorder(new LineBorder(Color.red, 1));
            } else if (addf.getText().equals("") || addf.getText().equals(null)) {
                addf.setBorder(new LineBorder(Color.red, 1));
            } else if (gpa.getText().equals("") || gpa.getText().equals(null)) {
                gpaf.setBorder(new LineBorder(Color.red, 1));
            } else if (ins_name.getText().equals("") || ins_name.getText().equals(null)) {
                ins_name.setBorder(new LineBorder(Color.red, 1));
            } else if (Double.parseDouble(gpaf.getText()) > 4) {
                gpaf.setBorder(new LineBorder(Color.red, 1));
            } else {
                try {
                    File f1 = new File("temp");
                    File stu_f = new File("student");
                    FileWriter fw = new FileWriter("temp", true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    PrintWriter pw = new PrintWriter(bw);

                    BufferedReader br = new BufferedReader(new FileReader("student"));
                    while ((line = br.readLine()) != null) {

                        String values[] = line.split(",");
                        if (values[0].equals(name)) {

                            System.out.println(id + values[1]);
                            pw.println(namef1.getText() + "," + id + "," + passf.getText() + "," + ins_name.getText() + "," + gpaf.getText() + "," + emailf.getText() + "," + addf.getText() + "," + gender);
                        } else {
                            pw.println(line);
                        }

                    }
                    pw.flush();
                    pw.close();
                    br.close();
                    bw.close();
                    fw.close();
                    String x = stu_f.getAbsolutePath();

                    stu_f.delete();

                    if (stu_f.exists()) {
                        System.out.println("not deleted");
                    }
                    File dump = new File(x);

                    f1.renameTo(dump);
                    System.out.println("hogya");

                    JFrame f = new JFrame();
                    JOptionPane.showMessageDialog(f, "Details Updated ");
                    jButton1.setVisible(false);

                    addf.setEditable(false);
                    emailf.setEditable(false);
                    gpaf.setEditable(false);
                    ins_name.setVisible(true);
                    combo.setVisible(false);

                    jButton1.setVisible(false);
                    namef1.setEditable(false);
                    passf.setEditable(false);

                    edit.setVisible(true);

                } catch (IOException e) {
                    System.out.println("som ting went vely wong");
                }
            }

        } else {
            namef1.setBorder(new LineBorder(Color.white, 1));
            passf.setBorder(new LineBorder(Color.white, 1));
            emailf.setBorder(new LineBorder(Color.white, 1));
            addf.setBorder(new LineBorder(Color.white, 1));
            gpaf.setBorder(new LineBorder(Color.white, 1));
            ins_name.setBorder(new LineBorder(Color.white, 1));

            if (namef1.getText().equals("") || namef1.getText().equals(null)) {
                namef1.setBorder(new LineBorder(Color.red, 1));
            } else if (passf.getText().equals("") || passf.getText().equals(null)) {
                passf.setBorder(new LineBorder(Color.red, 1));
            } else if (emailf.getText().equals("") || emailf.getText().equals(null) || !emailf.getText().contains("@")) {
                emailf.setBorder(new LineBorder(Color.red, 1));
            } else if (addf.getText().equals("") || addf.getText().equals(null)) {
                addf.setBorder(new LineBorder(Color.red, 1));
            } else if (gpa.getText().equals("") || gpa.getText().equals(null)) {
                addf.setBorder(new LineBorder(Color.red, 1));
            } else if (ins_name.getText().equals("") || ins_name.getText().equals(null)) {
                addf.setBorder(new LineBorder(Color.red, 1));
            } else {
                try {
                    File f1 = new File("temp");
                    File stu_f = new File("employee");
                    FileWriter fw = new FileWriter("temp", true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    PrintWriter pw = new PrintWriter(bw);

                    BufferedReader br = new BufferedReader(new FileReader("employee"));
                    while ((line = br.readLine()) != null) {

                        String values[] = line.split(",");
                        if (values[0].equals(name)) {

                            System.out.println(id + values[1]);
                            pw.println(namef1.getText() + "," + id + "," + passf.getText() + "," + ins_name.getText() + "," + gpaf.getText() + "," + emailf.getText() + "," + addf.getText() + "," + gender);
                        } else {
                            pw.println(line);
                        }

                    }
                    pw.flush();
                    pw.close();
                    br.close();
                    bw.close();
                    fw.close();
                    String x = stu_f.getAbsolutePath();

                    stu_f.delete();

                    if (stu_f.exists()) {
                        System.out.println("not deleted");
                    }
                    File dump = new File(x);

                    f1.renameTo(dump);
                    System.out.println("hogya");
                    JFrame f = new JFrame();
                    JOptionPane.showMessageDialog(f, "Details Updated ");

                    jButton1.setVisible(false);

                    addf.setEditable(false);
                    emailf.setEditable(false);
                    gpaf.setEditable(false);
                    ins_name.setVisible(true);
                    combo.setVisible(false);

                    jButton1.setVisible(false);
                    namef1.setEditable(false);
                    passf.setEditable(false);

                    edit.setVisible(true);

                } catch (IOException e) {
                    System.out.println("som ting went vely wong");
                }
            }

        }


    }//GEN-LAST:event_jButton1MouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new user_scr().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butMouseClicked
        // TODO add your handling code here:

        this.dispose();
        if (t == 2) {
            new scholar(gpaa).setVisible(true);
        } else{
            new jop_op().setVisible(true);
        }
    }//GEN-LAST:event_butMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stu_logged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stu_logged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stu_logged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stu_logged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stu_logged().setVisible(true);
            }
        });
    }
    String line;
    boolean T;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addf;
    private javax.swing.JButton back;
    private javax.swing.JButton but;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton edit;
    private javax.swing.JTextField emailf;
    private javax.swing.JLabel gpa;
    private javax.swing.JTextField gpaf;
    public javax.swing.JLabel ins_n;
    private javax.swing.JTextField ins_name;
    private javax.swing.JLabel insf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField namef1;
    private javax.swing.JTextField passf;
    // End of variables declaration//GEN-END:variables
}
