/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smartcityg;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class add_scholar extends javax.swing.JFrame {

    String ins;

    /**
     * Creates new form add_scholar
     */
    public add_scholar(String insn) {
        ins = insn;
        initComponents();
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
       table.setRowHeight(30);
       
    }

    public add_scholar() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        srf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(930, 620));
        setMinimumSize(new java.awt.Dimension(930, 620));
        setPreferredSize(new java.awt.Dimension(930, 620));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Scholarship");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 130, 170, 40);

        jLabel3.setVisible(true);
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setLabelFor(scf);
        jLabel3.setText("%");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 180, 16, 30);

        scf.setBackground(new java.awt.Color(95, 17, 131));
        scf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        scf.setForeground(new java.awt.Color(255, 255, 255));
        scf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scfMouseClicked(evt);
            }
        });
        scf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scfActionPerformed(evt);
            }
        });
        scf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                scfKeyPressed(evt);
            }
        });
        getContentPane().add(scf);
        scf.setBounds(80, 180, 110, 30);

        jLabel4.setBackground(new java.awt.Color(95, 17, 131));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Scholarship Requirement");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 130, 290, 40);

        srf.setBackground(new java.awt.Color(95, 17, 131));
        srf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        srf.setForeground(new java.awt.Color(255, 255, 255));
        srf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                srfKeyPressed(evt);
            }
        });
        getContentPane().add(srf);
        srf.setBounds(350, 180, 120, 30);

        jScrollPane1.setBackground(new java.awt.Color(95, 17, 131));
        jScrollPane1.setForeground(new java.awt.Color(245, 245, 245));

        table.setBackground(new java.awt.Color(95, 17, 131));
        table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Scholarship", "Requiremnet"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 280, 470, 340);

        jButton1.setBackground(new java.awt.Color(95, 17, 131));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Scholarship");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(700, 180, 170, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.red);
        jLabel5.setText("Requirement cant be greater than 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 210, 230, 20);

        jButton2.setBackground(new java.awt.Color(95, 17, 131));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Done");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(700, 240, 170, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.red);
        jLabel6.setText("scholarship cant be greater than 100%");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 210, 250, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smartcityg/modern-city-at-night-cartoon-background-vector-23716650.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 930, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
                    scf.setBorder(new LineBorder(Color.WHITE, 1));
                    srf.setBorder(new LineBorder(Color.WHITE, 1));

        double sr = 0;
        double sc = 0;

        try {
            sr = Double.parseDouble(srf.getText());
            sc = Double.parseDouble(scf.getText());

        } catch (NumberFormatException e) {
        }

        if (scf.getText().equals(null) || scf.getText().equals("")) {
            scf.setBorder(new LineBorder(Color.red, 1));
        } else if (srf.getText().equals("") || srf.getText().equals(null)) {
            scf.setBorder(new LineBorder(Color.red, 1));

        } else {

            if (sr > 4) {
                srf.setText("");
                srf.setBorder(new LineBorder(Color.red, 1));
                jLabel5.setVisible(true);
            } else if (sc > 100) {
                scf.setText("");
                scf.setBorder(new LineBorder(Color.red, 1));
                jLabel6.setVisible(true);
            } else {
                try {
                    FileWriter fw = new FileWriter("scholarship", true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    PrintWriter pw = new PrintWriter(bw);
                    pw.println(ins + "," + scf.getText() + "," + srf.getText());

                    pw.flush();
                    pw.close();
                    bw.close();
                    fw.close();

                } catch (IOException e) {
                }

                String data[] = {scf.getText(), srf.getText()};
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.addRow(data);
                
                scf.setText("");
                srf.setText("");

            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void scfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scfMouseClicked
        System.out.println("bbb");
    }//GEN-LAST:event_scfMouseClicked

    private void scfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_scfKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            scf.setEditable(false);
        } else {
            scf.setEditable(true);
        }
    }//GEN-LAST:event_scfKeyPressed

    private void srfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srfKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            srf.setEditable(false);
        } else {
            srf.setEditable(true);
        }
    }//GEN-LAST:event_srfKeyPressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new admin_logged().setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void scfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_scholar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_scholar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_scholar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_scholar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_scholar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField scf;
    private javax.swing.JTextField srf;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
